create or replace view POWERDB.PLOG.TABLEAU_REFRESH_VW(
	STATUSDATE,
	TABLEAU_NAME,
	TABLE_NAMES,
	FLAG
) as
with 
  STREAM_ALL as
(  
    select TABLE_NAME,STATUSTIME::date STATUSDATE,avg(ROW_COUNT) ROW_COUNT_AVG from POWERDB.PLOG.STREAM_LOG
    where METADATA$ACTION='INSERT'
    group by TABLE_NAME,STATUSDATE
),
  PER_CHANGE as
(
    select C.VIEW_NAME as TABLEAU_NAME,a.TABLE_NAME as BASE_TABLES,c.BASE_TABLES_COUNT,a.STATUSDATE,
    round(avg(a.ROW_COUNT_AVG),2) as ROW_COUNT_AVGR,round(avg(b.ROW_COUNT_AVG),2) as ROW_COUNT_AVG_5,
    round((ROW_COUNT_AVGR-ROW_COUNT_AVG_5)/ROW_COUNT_AVGR,2) as ROW_PER_CHANGE,
    case when ROW_PER_CHANGE between -20 and 20 then 'TRUE' 
    when ROW_COUNT_AVGR is null or ROW_COUNT_AVG_5 is null then null else 'FLASE'
    end as TRUE_FALSE
    from STREAM_ALL A 
    INNER JOIN
    STREAM_ALL B
    on a.TABLE_NAME=b.TABLE_NAME and b.STATUSDATE between a.STATUSDATE-5 and a.STATUSDATE
    INNER JOIN 
    (select VIEW_NAME,value as TABLE_NAME,count(*) over(partition by VIEW_NAME) as BASE_TABLES_COUNT from POWERDB.PLOG.TABLEAU_REFRESH_DETAILS a,
    lateral split_to_table(a.TABLE_NAMES,',')) C
    on a.TABLE_NAME=c.TABLE_NAME
    group by TABLEAU_NAME,BASE_TABLES,BASE_TABLES_COUNT,a.STATUSDATE
) 
    select STATUSDATE,TABLEAU_NAME,listagg(BASE_TABLES,',') as TABLE_NAMES ,iff(sum(iff(TRUE_FALSE='TRUE',1,0))=BASE_TABLES_COUNT,'TRUE','FALSE') FLAG 
    from PER_CHANGE group by STATUSDATE,TABLEAU_NAME,BASE_TABLES_COUNT
--End of view POWERDB.PLOG.TABLEAU_REFRESH_VW 
;